### ISSUE TITLE
Konfiguration lässt sich in REDAXO 5.6 nicht speichern

### ISSUE THREAD

**Issue by isospin** [FriendsOfREDAXO/yrewrite_scheme#12]
Nachem in REDAXO 5.6 z.B. das Schema umgestellt und gespeichert wurde steht es immer noch auf Standard.

**Comment by skerbis** [comment]
Wird mit REDAXO 5.6.1 behoben. https://github.com/redaxo/redaxo/commit/7716feb8bf103237626dbbf55355be53b2f99b04
