### ISSUE TITLE
Mehr SEO42-Magie (URL-Weiterleitungstypen)

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/yrewrite_scheme#14]
Erinnerungsstütze für @skerbis 

![image](https://user-images.githubusercontent.com/3855487/61364514-4a786900-a886-11e9-9e9e-c5ed696abbae.png)

* Weiterleitungstypen (intern, extern, Medienpool, keine URL...) an einer geeigneten Stelle definieren können
* verständliche, einfach gehaltene GUI für Redakteure (siehe SEO42)
* Kompatibilität zur Verwendung in REX_LIST
* * bspw. dadurch, indem Weiterleitungstypen wie in SEO42 am Artikel definiert werden
* * ggf. visuelles Feedback in der Struktur-Übersicht (anderes Kategorie-Icon, zusätzliche Spalte)

**Comment by skerbis** [comment]
> bspw. dadurch, indem Weiterleitungstypen wie in SEO42 am Artikel definiert werden
ich würde das so nicht machen und stattdessen eine Verwaltung dafür anlegen mit REX_Form oder YForm.

**Comment by alexplusde** [comment]
Wenn es das war, was du mir die ganze Zeit klarmachen wolltest, dann bin ich damit vollkommen D'accord, weil es imho eine gleichermaßen gute Usability bei der Eingabe gibt und eine gute Übersicht schafft.

(Sollte ein Artikel in der Struktur davon betroffen sein, dass eine Weiterleitung vorgeschaltet wurde - Szenarien gibt's, bspw. bei vorübergehenden Weiterleitungen oder vorbereitenden Maßnahmen - dann benötigt man dennoch einen Hinweis in der Editieransicht oder Strukturübersicht)

**Comment by skerbis** [comment]
denke aktuell, dass es in https://github.com/FriendsOfREDAXO/xcore besser aufgehoben wäre

**Comment by tbaddade** [comment]
sehe das eher in yrewrite selber

**Comment by skerbis** [comment]
Auch gut

**Comment by skerbis** [comment]
Sehe das auch so wie @tbaddade

**Comment by alexplusde** [comment]
Wurde das nicht schon Mal in YRewrite diskutiert und abgelehnt? Zumindest bei einem REDAXO-Tag gab es da eine Absage, da bin ich mir recht sicher.

Kann das Issue gerne nochmal in YRewrite aufmachen.

**Comment by skerbis** [comment]
Lassen wir’s erstmal auf. Da 3.1 die Schemen von den Funktionen trennt, besteht jetzt eine Chance es in yrewrite scheme zu realisieren. Cool wäre wenn das custom Widget für die Metadaten zur Verfügung stünde @joachimdoerr - dann wäre es mit einem einzigen Eingabefeld leicht realisierbar

**Comment by alexplusde** [comment]
Nach Hannover stellte sich heraus, dass dieses Thema nicht angegangen wird, bis REDAXO verschiedene Inhaltstypen abseits von Artikeln unterstützt. Deswegen würde ich es doch gerne in YRewrite oder hier via FOR umgesetzt sehen.

**Comment by skerbis** [comment]
Dieses Addon stellt nur Schemes bereit. Es wäre abseits seiner Funktion. Daher close ich das hier

**Comment by alexplusde** [comment]
Ich denke, dann habe ich ja jetzt einen Ort, wo ich das Feature umsetzen kann ;)

**Comment by skerbis** [comment]
👍
