### ISSUE TITLE
REDAXO-4-URL-Kompatibilität - clang-id optional um 1 abziehen

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/yrewrite_scheme#15]
die 1. clang_id war bisher `0`, jetzt ist sie `1` - sollte die Kompatibilität zu alten URLs beibehalten werden, müssten alle clang-ids in R5 bei YRewrite um 1 abgezogen werden.

**Comment by skerbis** [comment]
Schema wurde entfernt

**Comment by alexplusde** [comment]
Schade!
