### ISSUE TITLE
REDAXO-4-URL-Kompatibilität: Startseite weiterhin unter Artikel-URL aufrufbar lassen

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/yrewrite_scheme#16]
Der Startartikel ist bspw. nicht mehr unter /1-0-Startseite.html aufrufbar. Hier sollte eine Weiterleitung auf / erfolgen.

**Comment by tbaddade** [comment]
Ginge das nicht mit einer Weiterleitung direkt im AddOn?

**Comment by alexplusde** [comment]
Das ist ein guter Workaround, von der Einstellung `Schema REDAXO 3/4.x` erwarte ich das dennoch :)

**Comment by skerbis** [comment]
Das Schema haben wir entfernt https://github.com/FriendsOfREDAXO/yrewrite_scheme/releases/tag/3.0.0
