### ISSUE TITLE
Addon Umbennen?

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/yrewrite_scheme#2]
Da das wort schemes in vielen kontexten genutzt wird finde ich sollte die bezeichnung etwas weniger generische sein

Vorschlag
- yrewrite_schemes

**Comment by schuer** [comment]
+1

**Comment by skerbis** [comment]
passiert gerade

**Comment by gharlan** [comment]
Falls man #3 umsetzt, müsste man eventuell nochmal neu über den Namen nachdenken. Eventuell würde es dann schon reichen, das "s" am Ende zu entfernen, da es ja nur noch ein konfigurierbares Schema wäre.

**Comment by schuer** [comment]
Sorry, dass ich nochmal einhake, aber wäre der von Markus vorgeschlagene Name yrewrite_schemes nicht sinnvoller? Das AddOn basiert ja auf yrewrite, und damit wäre es einfacher verständlich und auch einfacher zu finden, weil es im Verzeichnis neben yrewrite gelistet würde.

**Comment by gharlan** [comment]
Finde ich auch etwas besser. Bloß wegen #3 würde ich es in der Einzahl belassen, also `yrewrite_scheme`

**Comment by skerbis** [comment]
Soll ich das Release zurückziehen. - Jetzt ist's zu spät

**Comment by schuer** [comment]
Ich würde sagen ja, aber am Ende entscheidest du als Lead, @skerbis.

**Comment by skerbis** [comment]
ich bleibt bei url_scheme

**Comment by tbaddade** [comment]
> ich bleibt bei url_scheme

D.h. es wird auch später andere Rewriter unterstützen?

**Comment by skerbis** [comment]
Ich mach ja schon.

**Comment by schuer** [comment]
Viel besser! 👍 

<img width="521" alt="screenshot 2017-10-10 13 14 02" src="https://user-images.githubusercontent.com/1297466/31383871-ebd80fce-adbc-11e7-9cbf-bd2105034ff0.png">

**Comment by skerbis** [comment]
Gut, ich mach noch ein paar yAddOns ;-)
