### ISSUE TITLE
Readme : Verständnis OneLevel

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/yrewrite_scheme#20]
Der untere Hinweis scheint sich zu widersprechen.

>  innerhalb einer Sprache ... Indien ... Brasilien

Oder ist dies hier nicht möglich?
`example.tld/hi/malabar`
`example.tld/pt/malabar`

**Aus der Readme**

### 2. One Level

Implementiert ein kurzes URL-Schema für alle Unterseiten.

__Vorher:__

`example.tld/en/coffee/beans/india/malabar.html`  _(yrewrite 1)_  
`example.tld/en/coffee/beans/india/malabar/`  _(yrewrite 2)_  

__Nachher:__

`example.tld/en/malabar`  _(ohne suffix)_  

> ⚠️ Wichtig: Das Schema ist nur dann sinnvoll, wenn Seiten innerhalb einer Sprache __nicht mehrfach vorkommen__. Gäbe es etwa den Malabar-Kaffee nicht nur in 🇮🇳 Indien, sondern auch in 🇧🇷 Brasilien, sollte dieses URL-Schema besser nicht verwendet werden!

**Comment by schuer** [comment]
Innerhalb einer Sprache geht nicht:

example.tld/**en**/coffee/beans/**india**/malabar/
example.tld/**en**/coffee/beans/**brasilia**/malabar/

ergibt beides example.tld/en/malabar, und damit einen Konflikt.

In unterschiedlichen Sprachen geht:

example.tld/**de**/coffee/beans/**india**/malabar/
example.tld/**en**/coffee/beans/**india**/malabar/

ergibt

example.tld/de/malabar
example.tld/en/malabar

Gerne re-open, falls noch nicht geklärt.
