### ISSUE TITLE
Sprache berücksichtigen lib/yrewrite_url_schemes.php:63

### ISSUE THREAD

**Issue by mg-gundb** [FriendsOfREDAXO/yrewrite_scheme#23]
`if ($art->isStartArticle() && ($cats = $art->getCategory()->getChildren(true)) && !rex_article_slice::getFirstSliceForCtype(1, $art->getId(), rex_clang::getCurrentId())) {`

**rex_clang::getCurrentId()** durch **$art->getClang()** ersetzen

**Comment by tbaddade** [comment]
Kannst du das Problem genauer erklären?

> rex_clang::getCurrentId() durch $art->getClang()

Warum sollte das ersetzt werden? Beides liefert die Sprache.

**Comment by mg-gundb** [comment]
Hallo Thomas

Entschuldige, ein salopper Eintrag, habe den als Reminder für Thomas Skerbis gesetzt. 
Der Auslöser kommt von hier: https://friendsofredaxo.slack.com/archives/C1BAXLN2F/p1574946119136600 <https://friendsofredaxo.slack.com/archives/C1BAXLN2F/p1574946119136600>

Soll ich das in GitHub noch präzisieren?

gruess matthieu

**Comment by tbaddade** [comment]
> Soll ich das in GitHub noch präzisieren?

Wenn @skerbis weiß was hier gemeint ist, wäre alles gut. Ein Anderer wird sich das Issue mit den wenigen Infos vermutlich nicht annehmen können.

Zur Info: Die Nachrichten in Slack verschwinden irgendwann. Wir haben dort nur 10.000 frei. D.h., dein Link wird irgendwann ins Leere laufen.

**Comment by skerbis** [comment]
@tbaddade alles gut. Aus irgendeinem noch zu erforschenden Grund scheint `rex_clang::getCurrentId()` dort nicht zu greifen. Ich werde das analysieren. getClang aus der YRewrite-Class soll das Problem gelöst haben.

**Comment by skerbis** [comment]
Bezieht sich auf: https://github.com/FriendsOfREDAXO/yrewrite_scheme/blob/f8ba241fe7e0cd169e1badf894d91390aff1183f/lib/yrewrite_url_schemes.php#L63
