### ISSUE TITLE
Warning beim Ändern einer Sprache

### ISSUE THREAD

**Issue by pschuchmann** [FriendsOfREDAXO/yrewrite_scheme#26]
Gerade beim Ändern einer Sprache in Redaxo 5.10 und YRewrite 2.6 aufgetreten.
```
Warning: in_array() expects parameter 2 to be array, string given in redaxo/src/addons/yrewrite_scheme/lib/yrewrite_url_schemes.php on line 76
```

**Comment by skerbis** [comment]
Hat nicht direkt was mit der Sprache zu tun. 
https://github.com/FriendsOfREDAXO/yrewrite_scheme/commit/99dff490db950f7ffa465c4c1c257659c2b46ea6

**Comment by tyrant88** [comment]
Ui, da hatte ich Mist gebaut.
