### ISSUE TITLE
kompatibilität mit yrewrite 2.7

### ISSUE THREAD

**Issue by isospin** [FriendsOfREDAXO/yrewrite_scheme#28]
in yrewrite 2.7 gibt es das neue feature ` Startsprache automatisch gemäß Sprache des Client-Browsers, bevorzugte Sprache als Fallback `.  wenn man diese automatische umleitung aktiviert, ist `/` nur noch eine weiterleitung, und auch die bevorzugte sprache bekommt als startseite `/de/` (o.ä.). 

sobald yrewrite_scheme aktiviert ist, wird die url der bevorzugten sprache wieder zu '/'. 
das führt dazu, das die seite der hauptsprache für user, die diese sprache nicht im browser eingestellt haben nicht aufrufbar ist.

**Comment by isospin** [comment]
wenn ich diese zeile 50 auskommentiere, funktioniert es:
https://github.com/FriendsOfREDAXO/yrewrite_scheme/blob/ff0f0244eb00d81cb32cae04b5f44ea9c581c36b/lib/yrewrite_url_schemes.php#L50
```
        if ($domain->getStartId() == $art->getId()) {
            if ($domain->getStartClang() == $art->getClang()) {
         //       return '/';
            }
            return $this->getClang($art->getClang(), $domain) . $path_suffix;
        }
```
an der stelle müsste man also noch abfragen ob die sprachweiterleitung in yrewrite aktiviert wurde

**Comment by gharlan** [comment]
> an der stelle müsste man vermutlich noch abfragen ob die sprachweiterleitung in yrewrite aktiviert wurde...

Jupp genau: https://github.com/yakamara/redaxo_yrewrite/blob/83fa1c21ca48897c8280795c6d68a65ac8a5d6a8/lib/yrewrite/scheme.php#L82

**Comment by isospin** [comment]
wenn alles geklappt hat liegt hierzu nun ein pull request vor: https://github.com/FriendsOfREDAXO/yrewrite_scheme/pull/29

**Comment by skerbis** [comment]
Ist gemerged @isospin, bitte testen. Dann werde ich releasen.

**Comment by skerbis** [comment]
Leider musste ich den PR reverten, da fehlerhaft

13.07.2020 13:10:22 | ParseError | syntax error, unexpected '!' | redaxo/src/addons/yrewrite_scheme/lib/yrewrite_url_schemes.php | 49

Habe aber nicht verstanden warum

**Comment by skerbis** [comment]
ich werde mindestens yrewrite 2.7 voraussetzen.

**Comment by tyrant88** [comment]
Du setzt ne beta-Version vorraus?

**Comment by skerbis** [comment]
ja hier in der GitHub Variante aktuell ja. - Es wird erst verbindlich wenn yrewrite 2.7  im Installer ist.
