### ISSUE TITLE
Idee: Nur eine konfigurierbare Scheme-Klasse

### ISSUE THREAD

**Issue by gharlan** [FriendsOfREDAXO/yrewrite_scheme#3]
Im Moment kann man nur eine der angebotenen Scheme-Klassen wählen.
Man könnte auch einen anderen Ansatz wählen:
Eine Backend-Page, wo man sich das Schema zusammenklicken kann, und nur eine Scheme-Klasse, die gemäß den gewählten Optionen agiert. Also innerhalb der Scheme-Klasse die Optionen abfragen.

Vorteil wäre, dass man kombinieren kann. Zum Beispiel One Level zusammen mit einer der Weiterleitungs-Schemes.

**Comment by skerbis** [comment]
Wird sich mit 3.0 ändern.

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/yrewrite_scheme/releases/tag/3.0.0

**Comment by skerbis** [comment]
@gharlan https://github.com/FriendsOfREDAXO/yrewrite_scheme/releases/tag/3.1.0
