### ISSUE TITLE
Ersetzungs-Array anpassbar machen

### ISSUE THREAD

**Issue by omphteliba** [FriendsOfREDAXO/yrewrite_scheme#36]
Es wär super wenn der Ersetzungs-Array im Addon anpassbar wär. Um individuelle Umschreibungen wie z.B. "&" => "und" einfacher umzusetzen.

**Comment by skerbis** [comment]
@omphteliba leg los

**Comment by skerbis** [comment]
Siehe Readme. Dort ist ein Beispiel drin.
