### ISSUE TITLE
Neuen Unicode-Modus des Mutteraddons unterstützen

### ISSUE THREAD

**Issue by gharlan** [FriendsOfREDAXO/yrewrite_scheme#38]
YRewrite hat inzwischen einen eigenen Unicode-Modus, der auch Sprachen mit anderen Schriften (kyrillisch etc.) unterstützt.
Dieser Modus belässt auch die deutschen Umlaute wie sie sind (also "ä" wird nicht "ae").
Der Modus arbeitet mit einem recht speziellen Regex und noch ein paar speziellen Ersetzungen: https://github.com/yakamara/redaxo_yrewrite/blob/72564f4e33a68154aff424194c11f66b3bda2a28/lib/yrewrite/scheme.php#L131-L134

Der Modus lässt sich in den allgemeinen YRewrite-Einstellungen aktivieren.
Jedoch wenn man yrewrite_scheme installiert hat, lässt sich der Modus nicht 100% so nutzen.
Denn yrewrite_scheme ersetzt grundsätzlich erstmal viele der Umlaute:
https://github.com/FriendsOfREDAXO/yrewrite_scheme/blob/b6c370db9877ebd983237f6a263124c5178987b1/lib/yrewrite_url_schemes.php#L131-L135

Ich fände es schön, wenn man trotz yrewrite_scheme, den neuen Unicode-Modus 1:1 wie im Mutteraddon nutzen könnte, ohne diese zusätzlichen Zeichenersetzungen.
Ich bin mir aber unsicher, wie man das nun am besten hier integriert, da dieses Addon ja vorher schon, sprachspezifisch, einen eigenen Unicode-Modus hatte. 
Dieser Modus ersetzt aber eben einerseits trotzdem viele Umlaute.
Und andererseits ersetzt er einige Sonderzeichen nicht, die der yrewrite-unicode-modus hingegen ersetzt (per diesem speziellen regex, siehe oben), wenn ich das richtig sehe.
Beispiele siehe PR: https://github.com/yakamara/redaxo_yrewrite/pull/360
Ich glaube, dass der Unicode-Modus aus diesem Addon zum Beispiel die Emojis, und auch "&" etc. so in der URL lassen würde, was bei manchen Zeichen problematisch sein kann.

Also letztlich würde ich mir also eine Variante wünschen, wo dieses Addon einfach nur per `parent::normalize` an die Elternklasse weiterreicht, ganz ohne eigene Anpassungen.

**Comment by skerbis** [comment]
Aus meiner Sicht kann es ganz weg. Um nicht alle Urls mit einem Update zu zerstören, schlage ich vor, es als Auswahl bereitzustellen.

**Comment by tyrant88** [comment]
Klingt vernünftig.

**Comment by tyrant88** [comment]
wenn du @skerbis es nicht machst, mache ich es im Hacktober...

**Comment by skerbis** [comment]
Klar gerne
