### ISSUE TITLE
"Diese Kategorien aus URL entfernen" arbeitet ungenau

### ISSUE THREAD

**Issue by isospin** [FriendsOfREDAXO/yrewrite_scheme#45]
Die Option "Diese Kategorien aus URL entfernen" macht aus:

https://domain.tld/en/about/about_us/
https://domain.tld/en-us/

wenn die Kategorie 'About' entfernt werden soll

richtig wäre
https://domain.tld/en/about_us/

yrewrite_scheme: 3.6.2 / 3.7.0
REDAXO:  5.15.1
PHP: 8.2.10

**Comment by isospin** [comment]
super, vielen dank!
jetzt wird aus
https://domain.tld/en/about/about-us/
https://domain.tld/en/aboutus/
das leerzeichen wird ignoriert

**Comment by tyrant88** [comment]
![Zwischenablage-1](https://github.com/FriendsOfREDAXO/yrewrite_scheme/assets/1277494/e47a2c1e-c0a3-4e7c-bc18-b6d96c4d24a6)

**Comment by tyrant88** [comment]
Ah ein Leerzeichen, sagst du!
Also der Artikel heißt "about us"?

**Comment by isospin** [comment]
![rewrite_scheme](https://github.com/FriendsOfREDAXO/yrewrite_scheme/assets/1148347/698699e2-1d02-404b-8881-3177c1455f72)

**Comment by isospin** [comment]
ja, 'about us' das hab ich erst oben falsch geschrieben...

**Comment by tyrant88** [comment]
Sei so gut und nenn den Artikle mal um, und dann wieder zurück wie es sein soll...
![Zwischenablage-1](https://github.com/FriendsOfREDAXO/yrewrite_scheme/assets/1277494/26baa136-4a42-426a-952d-0f1e03af1534)
Denn bei mir klappt es auch mit einem Leerzeichen

**Comment by isospin** [comment]
bei mir leider nicht
vielleicht liegt esa aber auch an den weiteren einstellungen:
![grafik](https://github.com/FriendsOfREDAXO/yrewrite_scheme/assets/1148347/a55cde56-e397-428f-92b1-6591df4d6a8a)

**Comment by isospin** [comment]
ah, verstehe...: die seite hat auch einen 'Visit us' artikel mit der url '/en/visit-us/' aber nachdem ich den namen wie oben beschrieben einmal geändert habe wurde daraus auch '/en/visitus/'
vielen dank!
